name: Update GitHub Stats
on:
  schedule:
    - cron: '0 3 * * *' # 每天北京时间11点自动更新
  workflow_dispatch: # 允许手动触发更新
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: 生成简洁版GitHub统计卡片
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          # 去掉了有bug的hide_border参数
          options: >
            username=chinabing
            &show_icons=true
            &theme=tokyonight
            &hide=contribs,reviews,discussions_started,discussions_answered,prs_merged,prs_merged_percentage
            &card_width=450
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 提交并推送卡片
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          git commit -m "自动更新GitHub统计卡片" || exit 0
          git push
